In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer



```
tf.keras.preprocessing.text.Tokenizer(
    num_words=None,
    filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
    lower=True,
    split=' ',
    char_level=False,
    oov_token=None,
    analyzer=None,
    **kwargs
)
```


```
num_words	the maximum number of words to keep, based on word frequency. Only the most common num_words-1 words will be kept.

The num_words parameter used in the initializer specifies the
maximum number of words minus one (based on frequency) to keep
when generating sequences.
```




In [2]:
sentences = [
    'i love my dog',
    'I, love my cat'
    ]

# Initialize the Tokenizer class
tokenizer = Tokenizer(num_words = 100)

# .fit_on_texts
tokenizer.fit_on_texts(sentences)

# Get the indices and print it
word_index = tokenizer.word_index
print(word_index)

{'i': 1, 'love': 2, 'my': 3, 'dog': 4, 'cat': 5}


## Text to Sequences





In [5]:


sentences = [
    'I love my dog',
    'I love my cat',
    'You love my dog!',
    'Do you think my dog is amazing?'
]
tokenizer = Tokenizer(num_words = 100, oov_token="<OOV>")

tokenizer.fit_on_texts(sentences)

word_index = tokenizer.word_index

print(word_index)

sequences = tokenizer.texts_to_sequences(sentences)

print(sequences)

{'<OOV>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}
[[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]


Padding



```
tf.keras.utils.pad_sequences(
    sequences,
    maxlen=None,
    dtype='int32',
    padding='pre',
    truncating='pre',
    value=0.0
)
```


```
maxlen	Optional Int, maximum length of all sequences. If not provided, sequences will be padded to the length of the longest individual sequence.
```




In [7]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [8]:
padded = pad_sequences(sequences, maxlen = 5)

print(padded)

[[ 0  5  3  2  4]
 [ 0  5  3  2  7]
 [ 0  6  3  2  4]
 [ 9  2  4 10 11]]


## Work on test

In [9]:
test_data = [
    'i really love my dog',
    'my dog loves my manatee'
]

In [10]:
test_sequences = tokenizer.texts_to_sequences(test_data)

print(test_sequences)

[[5, 1, 3, 2, 4], [2, 4, 1, 2, 1]]


In [11]:
# padding

padding_test_sequences = pad_sequences(test_sequences, maxlen = 10)

print(padding_test_sequences)

[[0 0 0 0 0 5 1 3 2 4]
 [0 0 0 0 0 2 4 1 2 1]]
