In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Introduction to Tensor
# Manipulating Tensors
# Tensors and Numpy

In [3]:
# Version of tf
print(tf.__version__)

2.13.0


### Create tensors with tf.constant()

In [4]:
scalar = tf.constant(7)

In [5]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Check Dimension

In [7]:
scalar.ndim #Scalar

0

In [8]:
# Create Vector

In [9]:
vector = tf.constant([10, 10])

In [10]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [11]:
vector.ndim

1

In [12]:
matrix = tf.constant([[1,2,3],
                      [2,3,4],
                      [4,5,6]])

In [13]:
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]], dtype=int32)>

In [14]:
matrix.ndim

2

In [15]:
# specify dtype

In [16]:
matrix2 = tf.constant([[7, 2],
                       [3, 4]], dtype = tf.float16)

In [17]:
matrix2

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[7., 2.],
       [3., 4.]], dtype=float16)>

In [18]:
# Create Tensor

In [19]:
tensor = tf.constant([[[1,2,3],
                       [3,4,5]],
                      [[6,7,8],
                      [9,10,11]]])

In [20]:
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]], dtype=int32)>

In [21]:
tensor.ndim

3

In [22]:
tensor2 = tf.constant([[[1,2],
                       [3,4]],
                      [[6,7],
                      [9,10]],
                       [[11,12],
                        [13,14]]])

In [23]:
tensor2

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 6,  7],
        [ 9, 10]],

       [[11, 12],
        [13, 14]]], dtype=int32)>

In [24]:
tensor2.ndim

3

In [25]:
tensor2.shape  #3 times 2x2 matrix

TensorShape([3, 2, 2])

### Create tensor with tf.Variable

In [26]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [27]:
changeable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])

In [28]:
changeable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [29]:
# Lets try change changable .assign()

In [30]:
changeable_tensor[1].assign(8)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([10,  8], dtype=int32)>

In [31]:
changeable_tensor #It is change

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  8], dtype=int32)>

In [32]:
# unchangable_tensor[0].assign(9)

In [33]:
tf.Variable(unchangable_tensor) # Transform into Variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

### Creating random tensor

In [34]:
#seed
random1 = tf.random.Generator.from_seed(42)

random1 = random1.normal(shape= (3, 2))


In [35]:
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [36]:
#also can put seed

In [37]:
random2 = tf.random.normal(shape = (3,2), seed = 42)

In [38]:
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.28077507, -0.13775212],
       [-0.67632955,  0.02458041],
       [-0.8935846 , -0.8284734 ]], dtype=float32)>

In [39]:
# but different :(


In [40]:
random3 = tf.random.normal(shape = (3,2), seed = 42)

In [41]:
random3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.01448264,  1.9438368 ],
       [-0.5893153 ,  1.15643   ],
       [-0.42452306,  1.2512863 ]], dtype=float32)>

In [42]:
random2 = tf.random.normal(shape = (3,2), seed = tf.random.set_seed(42))
random3 = tf.random.normal(shape = (3,2), seed = tf.random.set_seed(42))
random2, random3
# now seed work :D

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.3274685, -0.8426258],
        [ 0.3194337, -1.4075519],
        [-2.3880599, -1.0392479]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.3274685, -0.8426258],
        [ 0.3194337, -1.4075519],
        [-2.3880599, -1.0392479]], dtype=float32)>)

### Shuffle the order of the elements in a tensor

In [43]:
# Shuffle a tensor(valuable for when you want to shuffle your data)

In [44]:
not_shuffled = tf.constant([[7, 10],
                            [2, 3],
                            [12, 8]])

In [45]:
tf.random.shuffle(not_shuffled)  # shuffle dimension 0 "prevent row"

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12,  8],
       [ 7, 10],
       [ 2,  3]], dtype=int32)>

In [46]:
tf.random.shuffle(not_shuffled, seed = tf.random.set_seed(42))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  3],
       [12,  8],
       [ 7, 10]], dtype=int32)>

In [47]:
tf.random.set_seed(42) # global random seed
print(tf.random.shuffle(not_shuffled, seed = 21)) # operational random seed
print(tf.random.shuffle(not_shuffled, seed = 82))


tf.Tensor(
[[ 2  3]
 [12  8]
 [ 7 10]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  3]
 [ 7 10]
 [12  8]], shape=(3, 2), dtype=int32)


### Creating tensor with numpy (otherways)

In [48]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
tf.ones((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [50]:
tf.ones(3)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [51]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [52]:
tf.ones((1,3))

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 1., 1.]], dtype=float32)>

In [53]:
# Turn numpy array to tensor

In [54]:
numpy_A = np.random.randn(3,2)

In [55]:
numpy_A

array([[ 0.55271915, -0.63801626],
       [ 0.2261617 , -0.73582881],
       [-0.46469494, -0.9750267 ]])

In [56]:
numpy_B = np.arange(1, 25)
numpy_B

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [57]:
numpy_B.reshape((3,-1))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [58]:
tensor_B = tf.constant(numpy_B)

In [59]:
tensor_B

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [60]:
tensor_B = tf.constant(numpy_B, shape = (3,8))

In [61]:
tensor_B

<tf.Tensor: shape=(3, 8), dtype=int64, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])>

In [62]:
tf.reshape(tensor_B ,(2,-1))

<tf.Tensor: shape=(2, 12), dtype=int64, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])>

In [63]:
tf.reshape(tensor_B ,(2,2,-1))

<tf.Tensor: shape=(2, 2, 6), dtype=int64, numpy=
array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]])>

### Getting info form tensors


Attributes
*   Shape ---> tensor.shape
*   Rank  ---> tensor.ndim
*   Size  ---> tf.size(tensor)
*   Axis or Dimension ---> tensor[0], tensor[:,1]




In [64]:
# Create rank 4 tensor (4dim)

In [65]:
tf.random.set_seed(42)
rank_4_tensor = tf.range(1,121)
rank_4_tensor = tf.reshape(rank_4_tensor, (2,3,4,5))

In [66]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]], dtype=int32)>

In [67]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]], dtype=int32)>

In [68]:
rank_4_tensor[:,0]

<tf.Tensor: shape=(2, 4, 5), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75],
        [76, 77, 78, 79, 80]]], dtype=int32)>

In [69]:
rank_4_tensor.shape, rank_4_tensor.ndim

(TensorShape([2, 3, 4, 5]), 4)

In [70]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

### Indexing and Expanding Tensors

In [71]:
 rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 6,  7]],

        [[21, 22],
         [26, 27]]],


       [[[61, 62],
         [66, 67]],

        [[81, 82],
         [86, 87]]]], dtype=int32)>

## Add Extra Dimension

In [72]:
rank_2_tensor = tf.reshape(tf.range(1,7), shape = (2,3))

In [73]:
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [74]:
# Make it rank 3

In [75]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]  # in Python "..." means "all dimensions prior to"

In [76]:
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]], dtype=int32)>

In [77]:
# Or tf.expand_dims()

In [78]:
tf.expand_dims(rank_2_tensor, axis = -1)

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]], dtype=int32)>

### Manipulating Tensors

In [79]:
tensor1 = tf.constant([[10, 7], [3, 4]])
tensor1 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [80]:
tensor1 * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [81]:
tensor1 - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [82]:
# Matrix Multiplication

In [83]:
tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [84]:
tensor2 = tf.constant( [[2, 4], [6, 7]])

In [85]:
tensor1 @ tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[62, 89],
       [30, 40]], dtype=int32)>

In [86]:
tf.matmul(tensor1, tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[62, 89],
       [30, 40]], dtype=int32)>

In [87]:

# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

In [88]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [89]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [90]:
# tf.tensordot

In [91]:
tf.tensordot(tf.transpose(X), Y, axes = 1) # axes = 1 matmul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [92]:
tf.tensordot(tf.transpose(X), Y ,axes = 0) # outer product

<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
array([[[[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[21, 24],
         [27, 30],
         [33, 36]],

        [[35, 40],
         [45, 50],
         [55, 60]]],


       [[[14, 16],
         [18, 20],
         [22, 24]],

        [[28, 32],
         [36, 40],
         [44, 48]],

        [[42, 48],
         [54, 60],
         [66, 72]]]], dtype=int32)>

### Changing the datatype of a tensor

In [93]:
A = tf.range(1,5)
B = tf.range(1,5, dtype = tf.float32)

In [94]:
A, B

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>)

In [95]:
# tf.cast

In [96]:
tf.cast(A, dtype = tf.float32)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [97]:
# abs value
C = tf.constant([[-1,-3], [2, -10]])
tf.abs(C)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  3],
       [ 2, 10]], dtype=int32)>

### Aggregation

In [98]:
D = tf.constant(np.random.randint(1, 100, size = 50))
D

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([29, 50, 32, 54, 86, 17, 54,  9, 81, 32,  7,  6, 26, 69,  8, 47, 25,
        6, 77, 60, 76,  3, 97, 41, 98, 94, 87,  2, 87, 17, 28, 65, 95, 17,
       91, 54, 26, 28, 69, 65, 72, 44, 53, 14, 53, 31, 15, 31, 30,  4])>

In [99]:
# tf.reduce_min()
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [100]:
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [101]:
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [102]:
tf.reduce_sum(D)

<tf.Tensor: shape=(), dtype=int64, numpy=2262>

In [103]:
tf.argmax(D)

<tf.Tensor: shape=(), dtype=int64, numpy=24>

In [104]:
tf.argmin(D)

<tf.Tensor: shape=(), dtype=int64, numpy=27>

In [105]:
D_reshape = tf.reshape(D, shape = (5, -1))

In [106]:
D_reshape

<tf.Tensor: shape=(5, 10), dtype=int64, numpy=
array([[29, 50, 32, 54, 86, 17, 54,  9, 81, 32],
       [ 7,  6, 26, 69,  8, 47, 25,  6, 77, 60],
       [76,  3, 97, 41, 98, 94, 87,  2, 87, 17],
       [28, 65, 95, 17, 91, 54, 26, 28, 69, 65],
       [72, 44, 53, 14, 53, 31, 15, 31, 30,  4]])>

In [107]:
tf.reduce_min(D_reshape)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [108]:
tf.reduce_sum(D_reshape)

<tf.Tensor: shape=(), dtype=int64, numpy=2262>

In [109]:
tf.reduce_sum(D_reshape, axis = 0) # Row Sum

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([212, 168, 303, 195, 336, 243, 207,  76, 344, 178])>

In [110]:
tf.argmin(D_reshape)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([1, 2, 1, 4, 1, 0, 4, 2, 4, 4])>

### Squeezing a Tensor

In [111]:
E = tf.constant(np.random.randint(1, 100, 50), shape=(1,1,1,1,50))

In [112]:
E

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
array([[[[[80, 92, 71, 99, 68,  1, 43, 19, 42, 44, 52, 52, 78, 50, 80,
           29, 43, 95,  6, 39, 26, 20, 15, 78, 31, 89, 88, 66, 43, 47,
           88, 37, 30, 59, 31, 20, 68, 81, 42, 13, 88, 34, 78, 71, 12,
           30, 66, 59, 64, 40]]]]])>

In [113]:
tf.squeeze(E)

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([80, 92, 71, 99, 68,  1, 43, 19, 42, 44, 52, 52, 78, 50, 80, 29, 43,
       95,  6, 39, 26, 20, 15, 78, 31, 89, 88, 66, 43, 47, 88, 37, 30, 59,
       31, 20, 68, 81, 42, 13, 88, 34, 78, 71, 12, 30, 66, 59, 64, 40])>

In [114]:
F = tf.constant(np.random.randint(1, 100, 50), shape=(50,1,1,1,1))


In [115]:
tf.squeeze(F)

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 4, 59, 27, 47, 73,  7, 62, 81, 43,  6, 87, 61,  1, 79, 28, 46, 62,
       91, 92, 57, 33, 44, 65, 57, 38, 48, 45, 31, 72, 91, 81, 91, 44, 92,
       74,  1, 32, 98, 87, 16, 23, 67,  6, 60, 32, 87, 11, 35, 37, 36])>

In [116]:
G = tf.reshape(tf.constant(tf.range(1, 121)), shape = (2,3,4,5))

In [117]:
G

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]], dtype=int32)>

In [118]:
tf.squeeze(G)   # remove all dimensions of 1 from a tensor.

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]], dtype=int32)>

### One-Hot Encoding

In [119]:
some_list = [1,2,3,4]

tf.one_hot(some_list, depth = 4)



<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

### Squaring, log, square root

In [120]:
tf.square(np.arange(1,10))

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

### Manipulating tf.Variable tensors

In [121]:
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [122]:
# .assign

In [123]:
I.assign([2,3,32,64,33]) # Must be same shape when assign

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 2,  3, 32, 64, 33])>

In [124]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 2,  3, 32, 64, 33])>

In [125]:
I.assign_add([10] * 5)

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([12, 13, 42, 74, 43])>

### tensor.numpy()

In [126]:
J = tf.constant(np.array([3., 7., 10.]))

In [127]:
type(J)

tensorflow.python.framework.ops.EagerTensor

In [128]:
type(J.numpy())

numpy.ndarray

### @tf.function

In [129]:
def function(x, y):
    return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))

function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [130]:
@tf.function
def tf_function(x ,y):
    return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [131]:
# More faster

# Access GPU

In [133]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [134]:
!nvidia-smi

Sun Sep 17 21:15:08 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   71C    P0    31W /  70W |    361MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [1]:
import tensorflow as tf

In [2]:
# tab
# shift+ctrl+space